### ISSUE TITLE
Issue with RCLootCouncil Classic

### ISSUE THREAD

**Issue by evil-morfar** [solocommand/TitanSocial#25]
RCLootCouncil author here.

For your Classic version, in `TitanSocial.lua` line 102 you're calling `_G.GetNumClasses()` - that doesn't exist in Classic, and would normally prevent the for loop from doing anything. I reimplemented it for the Classic version of RCLootCouncil, in which it simply returns `_G.MAX_CLASSES`, i.e. the loop gets run.

This results in the call to `GetClassInfo()` which also doesn't exist in Classic, but which I've also reimplemented with the proper calls to `C_CreatureInfo.GetClassInfo()` which they kindly kept.

So basically your code should work, as I've reimplemented the missing functions - but of course Blizzard isn't that easy to work with. They left a gap in the class list because Death Knights have ID 6, which causes TitanSocial to use a `nil` as a table index. You can check with something like:
```lua
for i = 1, GetNumClasses() do
   print(GetClassInfo(i))
end
```
I suggest you do something for the Classic version (as the current implementation normally does nothing) or simply check for nils before updating the table. Do note `_G.MAX_CLASSES` is 10 (as excepted) but druids have ID 11 in `C_CreatureInfo.GetClassInfo()`.

**Comment by solocommand** [comment]
Thanks for the details!
