### ISSUE TITLE
Fails to work

### ISSUE THREAD

**Issue by galadius** [solocommand/TitanSocial#3]
Battle.net is working, up, and shows friends when I open the social window, however your addon fails when I mouse over, and looks like this <?>

error message when I mousover reads:

TitanSocial error: Interface\AddOns\TitanSocial\TitanSocial.lua:663: attempt to call upvalue 'BNGetNumFriendToons' (a nil value)

**Comment by solocommand** [comment]
Hi galadius,

The latest release isn't yet showing up in the Curse Client. Can you confirm you have the latest file installed?

You can download from [CurseForge](http://legacy.curseforge.com/media/files/913/617/TitanSocial-6.2.4-release3.zip) or [Github](https://github.com/solocommand/TitanSocial/archive/6.2.4-release3.zip).

We have an open support ticket with Curse to resolve the issue with the client, in the meantime you may have to download it manually.

**Comment by galadius** [comment]
Thank you, works fine.
