### ISSUE TITLE
is NOT updated on CURSE CLIENT

### ISSUE THREAD

**Issue by dasjames** [solocommand/TitanSocial#4]
per the curse homepage this add is UPDATED,  yet on CURSE CLIENT it is    6.1r32-release version, the updated version is not available,  as of   3/29/2016 9:32 am  est.

**Comment by solocommand** [comment]
Hi dasjames,

Thanks for the report, I know this issue is frustrating for many people.

I have an open support ticket with Curse about this issue. I haven't heard anything back from them yet, but I will update once I do.

**Comment by dasjames** [comment]
TY TY sir   i think it's fixed

**Comment by solocommand** [comment]
Nice! I do t have access to a machine with the client at the moment to test, but I'll close this out later if it's truly resolved.
