### ISSUE TITLE
Problem to see RealID contact play zone

### ISSUE THREAD

**Issue by NeOtHeNeO** [solocommand/TitanSocial#5]
Hi,

All is in the title. i can't see the zone where play my realid contact in wow

Is there any issu for this problem ?

**Comment by solocommand** [comment]
@NeOtHeNeO No issue that I know of, unless the Battle.net API bug has regressed. I will look into this ASAP.

**Comment by kballard** [comment]
This is a Blizzard API bug, which I will push a fix out for soon.

**Comment by kballard** [comment]
Fixed in release [6.2.4.4-beta](https://github.com/solocommand/TitanSocial/releases/tag/6.2.4.4-beta). Please try it out and let me know.
