### ISSUE TITLE
Problem with server's name display

### ISSUE THREAD

**Issue by Sebybear** [solocommand/TitanSocial#6]
Hello,

Don't know since when it displays like that (&asop;) in the server's name and if it's just me but wanted to ask you if it's normal. 
![bug titansocial](https://cloud.githubusercontent.com/assets/19172636/14990494/1c8a473e-115d-11e6-99e1-057fc0ad56ab.PNG)

![bug titansocial0](https://cloud.githubusercontent.com/assets/19172636/14990805/97debb30-115e-11e6-84b7-2187897a4fc1.PNG)

Thank you in advance

**Comment by kballard** [comment]
That's pretty weird. `&apos;` is an HTML entity. There's no reason at all why this should be showing up in WoW. Without looking into it (I don't know how I would do that unless the problem reproduces for me and I haven't noticed it), I'm inclined to say that this is a bug on Blizzard's side.

**Comment by kballard** [comment]
This is definitely a Blizzard API bug, but I have a workaround, which I will release soon.

**Comment by kballard** [comment]
Fixed in release [6.2.4.4-beta](https://github.com/solocommand/TitanSocial/releases/tag/6.2.4.4-beta). Please try it out and let me know.
